
columns = """
id, label, s, tx, ty, tz, r11, r12, r13, r21, r22, r23, r31, r32, r33, 
hand_dir_1, hand_dir_2, hand_dir_3,  thumb_dir_1, thumb_dir_2, thumb_dir_3, 
thumb_meta_center_1, thumb_meta_center_2, thumb_meta_center_3, thumb_meta_dir_1, 
thumb_meta_dir_2, thumb_meta_dir_3, 	thumb_prox_center_1, thumb_prox_center_2, 
thumb_prox_center_3, thumb_prox_dir_1, thumb_prox_dir_2, thumb_prox_dir_3, 	
thumb_int_center_1, thumb_int_center_2, thumb_int_center_3, thumb_int_dir_1, 
thumb_int_dir_2, thumb_int_dir_3, 	thumb_dist_center_1, thumb_dist_center_2, 
thumb_dist_center_3, thumb_dist_dir_1, thumb_dist_dir_2, thumb_dist_dir_3, 	
thumb_tip_pos_1, thumb_tip_pos_2, thumb_tip_pos_3, index_dir_1, index_dir_2, index_dir_3, 	
index_meta_center_1, index_meta_center_2, index_meta_center_3, index_meta_dir_1, index_meta_dir_2, 
index_meta_dir_3, 	index_prox_center_1, index_prox_center_2, index_prox_center_3, index_prox_dir_1, 
index_prox_dir_2, index_prox_dir_3, 	index_int_center_1, index_int_center_2, index_int_center_3, 
index_int_dir_1, index_int_dir_2, index_int_dir_3, 	index_dist_center_1, index_dist_center_2, 
index_dist_center_3, index_dist_dir_1, index_dist_dir_2, index_dist_dir_3, 	index_tip_pos_1, 
index_tip_pos_2, index_tip_pos_3, middle_dir_1, middle_dir_2, middle_dir_3, 	
middle_meta_center_1, middle_meta_center_2, middle_meta_center_3, middle_meta_dir_1, 
middle_meta_dir_2, middle_meta_dir_3, 	middle_prox_center_1, middle_prox_center_2, middle_prox_center_3, 
middle_prox_dir_1, middle_prox_dir_2, middle_prox_dir_3, 	middle_int_center_1, middle_int_center_2, 
middle_int_center_3, middle_int_dir_1, middle_int_dir_2, middle_int_dir_3, 	middle_dist_center_1, 
middle_dist_center_2, middle_dist_center_3, middle_dist_dir_1, middle_dist_dir_2, middle_dist_dir_3, 	
middle_tip_pos_1, middle_tip_pos_2, middle_tip_pos_3, ring_dir_1, ring_dir_2, ring_dir_3, 
ring_meta_center_1, ring_meta_center_2, ring_meta_center_3, ring_meta_dir_1, ring_meta_dir_2, 
ring_meta_dir_3, 	ring_prox_center_1, ring_prox_center_2, ring_prox_center_3, ring_prox_dir_1, 
ring_prox_dir_2, ring_prox_dir_3, 	ring_int_center_1, ring_int_center_2, ring_int_center_3, ring_int_dir_1, 
ring_int_dir_2, ring_int_dir_3, 	ring_dist_center_1, ring_dist_center_2, ring_dist_center_3, ring_dist_dir_1, 
ring_dist_dir_2, ring_dist_dir_3, 	ring_tip_pos_1, ring_tip_pos_2, ring_tip_pos_3, pinkie_dir_1, pinkie_dir_2, 
pinkie_dir_3, 	pinkie_meta_center_1, pinkie_meta_center_2, pinkie_meta_center_3, pinkie_meta_dir_1, 
pinkie_meta_dir_2, pinkie_meta_dir_3, 	pinkie_prox_center_1, pinkie_prox_center_2, pinkie_prox_center_3,
 pinkie_prox_dir_1, pinkie_prox_dir_2, pinkie_prox_dir_3, 	pinkie_int_center_1, pinkie_int_center_2, 
 pinkie_int_center_3, pinkie_int_dir_1, pinkie_int_dir_2, pinkie_int_dir_3, 	pinkie_dist_center_1, 
 pinkie_dist_center_2, pinkie_dist_center_3, pinkie_dist_dir_1, pinkie_dist_dir_2, pinkie_dist_dir_3, 	
 pinkie_tip_pos_1, pinkie_tip_pos_2, pinkie_tip_pos_3,
""".replace('\n', '')
columns = [col.strip() for col in columns.split(', ')]
[print(f'jsonText += "{label}: " + 0 + ",\\n";') for label in columns]